---
cops_django_name: djangoinstance
cops_django_project_module_name: "{{cops_django_name}}"
cops_django_settings_module: "{{cops_django_project_module_name}}.settings.instances.{{cops_django_deploy_env}}"
cops_django_py_ver: "3.7"
cops_django_deploy_env: "dev"
cops_django_docker_image_tag: "{{cops_django_name}}"
cops_django_default_docker_tag: "latest"
cops_django_docker_tag: "{{cops_django_default_docker_tag}}"
cops_django_tld_domain: example.com
cops_django_mail_domain: "{{ cops_django_tld_domain }}"
cops_django_default_gitref: "master"
cops_django_gitref: "{{cops_django_default_gitref}}"
cops_django_dir: "/srv/docker/{{cops_django_name}}"
cops_django_hostname: "{{cops_django_deploy_env}}-{{cops_django_name}}.{{cops_django_tld_domain}}"
cops_django_alternate_hostnames: [".{{cops_django_tld_domain}}"]
cops_django_secret_key: "SuperSecret"
cops_django_gateway: "{{ ansible_default_ipv4.address}}"
cops_django_composename: "{{cops_django_name}}"
cops_django_db_user: "secretJFCxwPHz99R9jIi"
cops_django_db_password: "secret4gzQNe3c8851VOJ"
cops_django_db_name: "{{cops_django_name}}"
cops_django_devmode: False
cops_django_build_args: "--no-cache django cron"
# backup could be remove in a-while when we have redeployed it everywhere
cops_django_restarted_services: "db redis django nginx backup cron"
cops_django_purge_volumes: [statics]
cops_django_sshargs: >-
  {% set k = hostvars[inventory_hostname].get(
                'ansible_ssh_private_key_file', '') %}
  {% if k%}-o IdentityFile={{k}} -o IdentitiesOnly=yes{%endif%}
  {% if (
      hostvars[inventory_hostname].ansible_connection|default('ssh')
     ) not in [ 'smart', 'local'] %}
  {{ hostvars[inventory_hostname].ssh_args | default('') }}
  {{ hostvars[inventory_hostname].ansible_ssh_args | default('') }}
  {{ hostvars[inventory_hostname].ansible_ssh_common_args | default('') }}
  {{ hostvars[inventory_hostname].ansible_ssh_extra_args | default('') }}
  {% endif %}
cops_django_build: false
cops_django_pull: true
cops_django_registries: []
#- {registry: registry.foo.net, username: foo, password: bar}
cops_django_compose_files: [docker-compose.yml, docker-compose-prod.yml]
cops_django_dc:
  docker-compose {% for i in cops_django_compose_files %} -f {{i}}{% endfor %}
  -p "{{cops_django_composename}}"
cops_django_default_from_email: noreply@{{cops_django_hostname}}
cops_django_server_email: "{{cops_django_default_from_email}}"
cops_django_email_server: mailcatcher
cops_django_email_host_user: ''
cops_django_email_host_password: ''
cops_django_email_host_port: 1025
cops_django_email_use_tls: 'False'
# free form for params inside dockerenv
cops_django_dotenv: |-
  APP_TYPE=django
  DJANGO_PY_VER={{ cops_django_py_ver }}
  DJANGO_NAME={{ cops_django_name }}
  COMPOSE_PROJECT_NAME={{cops_django_composename}}
  CI_COMMIT_SHA={{cops_django_gitref}}
  DJANGO_IMAGE={{ cops_django_docker_image }}
  DJANGO_IMAGE_VERSION={{cops_django_docker_tag}}
cops_django_dotenv_extra: ""
# free form for params inside dockerenv
cops_django_docker_env_extra: ""
# free form for params inside local.py
cops_django_localpy_extra: ""
# Normally playbook is in ./.ansible/playbooks
cops_django_code_dir: "{{playbook_dir}}/../.."
cops_django_code_rsync_opts: [
    "-azv",
    # include deploy projects base code
    "--include", "local/*-deploy",
    "--exclude", ".ansible",
    "--exclude", "local/*",
    "--exclude", ".git",
    "--exclude", ".tox",
    "--exclude", ".env",
    "--exclude", "docker.env"]
